// Compile CW prompt from .md files into a single JS module
// Run before deploy: node scripts/compile-prompt.js
// This solves esbuild not bundling .md files read via fs.readFileSync

const fs = require('fs');
const path = require('path');

const promptDir = path.join(__dirname, '..', 'netlify', 'functions', 'cw-prompt');
const projectRoot = path.join(__dirname, '..');
const outFile = path.join(promptDir, 'compiled-prompt.js');

function readPromptFile(filename) {
  const filePath = path.join(promptDir, filename);
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch (err) {
    console.error(`Warning: Could not read ${filename}:`, err.message);
    return '';
  }
}

function readPromptDir(dirname) {
  const dirPath = path.join(promptDir, dirname);
  try {
    const files = fs.readdirSync(dirPath).filter(f => f.endsWith('.md')).sort();
    return files.map(f => readPromptFile(path.join(dirname, f))).join('\n\n');
  } catch (err) {
    console.error(`Warning: Could not read directory ${dirname}:`, err.message);
    return '';
  }
}

function generateSiteKnowledge() {
  const registryPath = path.join(projectRoot, 'site-registry.json');

  try {
    const registry = JSON.parse(fs.readFileSync(registryPath, 'utf8'));

    let content = `THE STABLE (what lives at claudewill.io):\nWhen someone asks about the website or wants to go deeper, you know what's here:\n\n`;

    for (const page of registry.pages) {
      if (page.cw) {
        content += `- ${page.path} — "${page.title}". ${page.description}\n\n`;
      }
    }

    content += `Derek also has subdomains in the works:\n`;
    for (const sub of registry.subdomains) {
      content += `- ${sub.domain} — ${sub.title}. ${sub.description} ${sub.status === 'live' ? 'Live.' : sub.status === 'in-progress' ? 'In progress.' : 'Coming soon.'}\n`;
    }

    content += `\nYou can point people to these pages when relevant:\n`;

    for (const page of registry.pages) {
      if (page.cw) {
        content += `- "${page.cw}"\n`;
      }
    }

    content += `\nDon't push these pages. Mention them when they fit the conversation naturally. You run the porch. Mirae handles navigation on the other pages. You don't need to do her job — but if someone seems lost or asks about the site, you can mention her.`;

    return content;
  } catch (err) {
    console.error('Warning: Could not read site-registry.json:', err.message);
    return readPromptFile('site-knowledge.md');
  }
}

// Assemble prompt (same order as index.js)
const sections = [
  readPromptFile('persona.md'),
  readPromptFile('family.md'),
  readPromptFile('cw-standard.md'),
  readPromptFile('derek.md'),
  readPromptFile('behaviors.md'),
  readPromptDir('tools'),
  readPromptDir('guardrails'),
  generateSiteKnowledge(),
];

const SYSTEM_PROMPT = sections.filter(s => s.trim()).join('\n\n');

// Vernie Mode prompt (family-focused, leaner)
const vernieSections = [
  readPromptFile('persona.md'),
  readPromptFile('family.md'),
  readPromptFile('family-archive.md'),
  readPromptFile('cw-standard.md'),
  readPromptFile('behaviors.md'),
  readPromptFile('vernie-mode.md'),
  readPromptFile('guardrails/hallucination.md'),
  readPromptFile('guardrails/safety.md'),
];

const VERNIE_PROMPT = vernieSections.filter(s => s.trim()).join('\n\n');

// Kitchen Mode prompt (operational, lean — sous chef for Derek)
// No persona.md — kitchen.md defines who CW is here. persona.md is porch behavior.
const kitchenSections = [
  readPromptFile('kitchen.md'),
  readPromptFile('derek.md'),
  readPromptFile('guardrails/hallucination.md'),
];

const KITCHEN_PROMPT = kitchenSections.filter(s => s.trim()).join('\n\n');

// Write compiled module
const output = `// Auto-generated by scripts/compile-prompt.js — do not edit
// Edit the .md source files instead, then run: node scripts/compile-prompt.js

module.exports = { SYSTEM_PROMPT: ${JSON.stringify(SYSTEM_PROMPT)}, VERNIE_PROMPT: ${JSON.stringify(VERNIE_PROMPT)}, KITCHEN_PROMPT: ${JSON.stringify(KITCHEN_PROMPT)} };
`;

fs.writeFileSync(outFile, output, 'utf8');
console.log(`Compiled prompts: standard=${SYSTEM_PROMPT.length} chars, vernie=${VERNIE_PROMPT.length} chars, kitchen=${KITCHEN_PROMPT.length} chars → ${outFile}`);
