name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: .

  # You can add a deploy step here if you want to deploy to GitHub Pages, Netlify, or another service.
  # For now, this workflow just checks out the code and uploads it as an artifact for inspection.
